
default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [action]'
	@echo
	@echo 'Ex:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make config-install'
	@echo
	@echo '	$$ make kdebiglinux-config-install'
	@echo


.PHONY: help


config-install:
	@./config-install.sh
.PHONY: config-install


kdebiglinux-config-install:
	@./kdebiglinux-config-install.sh
.PHONY: kdebiglinux-config-install


desktop-layout:
	@./desktop-layout.sh
.PHONY: desktop-layout
